# Generated by Django 4.2.1 on 2023-05-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('name', models.CharField(default=False, max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('image', models.URLField(default=None)),
                ('release', models.DateField(default='2023-05-31')),
                ('lte_exists', models.BooleanField(default=0)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
    ]
